[build-system]
requires = ["setuptools", "wheel", "logging"]
build-backend = "setuptools.build_meta"

[project]
name = "loggers"
version = "1.0.0"
description = "robust and generic logging system for Python"
authors = [{name = "Elias Rodkey", email = "elias.rodkey@gmail.com"}]
license = {text = "MIT"}
dependencies = ["requests", "numpy"]  # List your package dependencies here