[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "super_logging"
version = "0.1.0"
description = "A short description of your package"
authors = [{name = "Elias Rodkey", email = "elias.rodkey@gmail.com"}]
license = {text = "MIT"}
dependencies = ["requests", "numpy"]  # List your package dependencies here